<?php
/**
 * Plugin Name: CMSS Secure Upload Directories
 * Description: Automatically blocks PHP/script execution in all user upload folders (year/month). Works for existing and future folders. Does NOT touch vendor folder.
 * Version: 1.0.0
 */

if (!defined('ABSPATH')) exit;

/* =============================================================
   The .htaccess content that blocks script execution
   ============================================================= */

function cmss_htaccess_content() {
    return "# Auto-generated by CMSS Secure Uploads Plugin\n"
         . "# Blocks PHP and script execution in user upload folders\n"
         . "Options -ExecCGI\n"
         . "<FilesMatch \"\.(php|php3|php4|php5|phtml|pl|py|jsp|asp|sh|cgi|exe|bat)$\">\n"
         . "    Order Deny,Allow\n"
         . "    Deny from all\n"
         . "</FilesMatch>\n";
}

/* =============================================================
   FIX 1: Auto-create .htaccess for every NEW upload folder
   WordPress creates new year/month folders automatically —
   this hook fires every time and secures the new folder.
   ============================================================= */

add_filter('upload_dir', 'cmss_secure_new_upload_dir');

function cmss_secure_new_upload_dir($uploads) {
    $folder = $uploads['path']; // e.g. .../uploads/2025/06

    // Skip vendor folder and any folder with "vendor" in path
    if (strpos($folder, 'vendor') !== false) return $uploads;

    // Skip if not a year/month folder (extra safety)
    $htaccess = $folder . '/.htaccess';

    // Create folder if it doesn't exist yet
    if (!file_exists($folder)) {
        wp_mkdir_p($folder);
    }

    // Create .htaccess if it doesn't exist
    if (!file_exists($htaccess)) {
        file_put_contents($htaccess, cmss_htaccess_content());
    }

    return $uploads;
}

/* =============================================================
   FIX 2: On plugin activation — secure ALL existing folders
   Loops through every existing year/month folder and adds
   .htaccess if missing. Runs once when plugin is activated.
   ============================================================= */

register_activation_hook(__FILE__, 'cmss_secure_all_existing_folders');

function cmss_secure_all_existing_folders() {
    $upload_base = wp_upload_dir();
    $base_path   = $upload_base['basedir']; // .../wp-content/uploads

    if (!is_dir($base_path)) return;

    // Loop through all folders inside uploads/
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($base_path, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );

    foreach ($iterator as $item) {
        if (!$item->isDir()) continue;

        $folder_path = $item->getPathname();

        // Skip vendor folder and any path containing vendor
        if (strpos($folder_path, 'vendor') !== false) continue;

        // Skip the base uploads folder itself (only target year/month subfolders)
        if ($folder_path === $base_path) continue;

        $htaccess_path = $folder_path . '/.htaccess';

        // Create .htaccess if missing
        if (!file_exists($htaccess_path)) {
            file_put_contents($htaccess_path, cmss_htaccess_content());
        }
    }

    // Also add .htaccess to base uploads folder
    $base_htaccess = $base_path . '/.htaccess';
    if (!file_exists($base_htaccess)) {
        file_put_contents($base_htaccess, cmss_htaccess_content());
    }
}

/* =============================================================
   FIX 3: Daily cron job — checks and fixes any missing .htaccess
   Catches any folder that was created outside of WordPress
   (e.g. manually via FTP or SVN)
   ============================================================= */

// Register cron schedule
add_filter('cron_schedules', function($schedules) {
    $schedules['daily_cmss'] = [
        'interval' => 86400, // 24 hours
        'display'  => 'Once Daily (CMSS Security Check)'
    ];
    return $schedules;
});

// Schedule the cron on plugin activation
register_activation_hook(__FILE__, 'cmss_schedule_security_cron');

function cmss_schedule_security_cron() {
    if (!wp_next_scheduled('cmss_daily_upload_security_check')) {
        wp_schedule_event(time(), 'daily_cmss', 'cmss_daily_upload_security_check');
    }
}

// Clear cron on plugin deactivation
register_deactivation_hook(__FILE__, function() {
    wp_clear_scheduled_hook('cmss_daily_upload_security_check');
});

// The actual cron job function
add_action('cmss_daily_upload_security_check', 'cmss_secure_all_existing_folders');

/* =============================================================
   FIX 4: Admin notice — shows status of upload folder security
   ============================================================= */

add_action('admin_notices', 'cmss_upload_security_status_notice');

function cmss_upload_security_status_notice() {
    // Only show on plugins page
    $screen = get_current_screen();
    if (!$screen || $screen->id !== 'plugins') return;

    $upload_base = wp_upload_dir();
    $base_path   = $upload_base['basedir'];
    $htaccess    = $base_path . '/.htaccess';

    if (file_exists($htaccess)) {
        echo '<div class="notice notice-success is-dismissible">
                <p><strong>CMSS Secure Uploads:</strong> ✅ Upload directories are protected. PHP execution is blocked in all user upload folders.</p>
              </div>';
    } else {
        echo '<div class="notice notice-error">
                <p><strong>CMSS Secure Uploads:</strong> ❌ Upload directory is NOT protected. 
                <a href="' . admin_url('admin.php?cmss_fix_uploads=1') . '">Click here to fix now</a></p>
              </div>';
    }
}

// Handle manual fix from admin notice link
add_action('admin_init', function() {
    if (isset($_GET['cmss_fix_uploads']) && current_user_can('manage_options')) {
        cmss_secure_all_existing_folders();
        wp_redirect(admin_url('plugins.php?cmss_fixed=1'));
        exit;
    }
});